site_name: ANT-AI
repo_url: !ENV [DOCS_REPO_URL, "https://gitlab.com/<org>/ant-ai"]
repo_name: !ENV [DOCS_REPO_NAME, "<org>/ant-ai"]

docs_dir: docs
extra_css:
    - stylesheets/extra.css

theme:
    name: material
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.tabs.indicator
        - navigation.instant
        - navigation.tracking
        - navigation.sections
        - content.code.copy
        - content.action.edit

    logo: assets/ant_icon_white.png
    favicon: assets/ant_icon_white.png

    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: black
          accent: deep purple
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: black
          accent: deep purple
          toggle:
              icon: material/brightness-4
              name: Switch to system preference

plugins:
    - search
    - section-index
    - awesome-nav
    - panzoom

    - gen-files:
          scripts:
              - docs/_gen_reference.py

    - mkdocstrings:
          handlers:
              python:
                  paths: ["src"]
                  options:
                      docstring_style: google
                      show_source: true
                      members_order: source
                      group_by_category: true
                      separate_signature: true
                      show_signature_annotations: true
                      annotations_path: brief
                      show_symbol_type_heading: true
                      signature_crossrefs: true
                      render_markdown: true
                      show_private_members: false

                      extensions:
                          - griffe_pydantic:
                                schema: true

markdown_extensions:
    - attr_list
    - md_in_html
    - admonition
    - pymdownx.details
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.tabbed
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
