from __future__ import annotations

import uuid
from collections.abc import AsyncIterator, Mapping
from contextvars import ContextVar
from typing import TYPE_CHECKING, Any, Literal, Protocol, get_args, runtime_checkable

from pydantic import BaseModel, ConfigDict, Field, PrivateAttr

from ant_ai.core.events import Event, FinalAnswerEvent, ToolCallingEvent
from ant_ai.core.message import Message
from ant_ai.core.types import InvocationContext, State
from ant_ai.tools.tool import Tool

if TYPE_CHECKING:
    from a2a.types import AgentCard

    from ant_ai.a2a.config import A2AConfig
    from ant_ai.agent.base import BaseAgent
    from ant_ai.workflow.workflow import Workflow


_peer_depth: ContextVar[int] = ContextVar("ant_ai_peer_depth", default=0)
"""Nesting depth of peer-to-peer calls within a single round.

In visibility mode an agent can call a peer that calls a peer, synchronously,
so "one graph per round" is only true if the nesting is bounded and recorded.
"""


class ParticipantProfile(BaseModel):
    """Capability text a matcher works over — the static half of an advertisement.

    Sourced from the AgentCard (remote) or `BaseAgent.description` (local); it
    is never invented by the topology layer.
    """

    name: str
    description: str = ""
    tags: tuple[str, ...] = ()

    def as_text(self) -> str:
        """Flatten to a single string, for use as a descriptor fallback."""
        tags = f" Tags: {', '.join(self.tags)}." if self.tags else ""
        return f"{self.name}. {self.description}{tags}".strip()


type Reaction = Literal["consume", "wait", "discard", "reroute"]
"""What a participant may declare it did with a message it was delivered.

`consume` acted on it, `wait` kept it for a later turn, `discard` dropped it,
`reroute` handed it to someone better placed. Absent means consumed.
"""

REACTIONS: dict[str, Reaction] = {
    label: label for label in get_args(Reaction.__value__)
}
"""The same vocabulary as a lookup, for resolving what a model answered.

A dict rather than a tuple because a membership test proves nothing to a type
checker: `label in REACTIONS` still leaves a `str`, and the record's edges are
typed by this vocabulary.
"""


class Envelope(BaseModel):
    """One message generated by a participant."""

    id: str = Field(default_factory=lambda: uuid.uuid4().hex)
    sender: str
    content: str
    visibility: Literal["public", "private"] = "private"
    round: int = 0
    parents: tuple[str, ...] = ()
    """Ids of the messages this one derives from.

    The lineage chain, and the only way to ask a causal question about a run:
    which contributions a given one descends from. Populated by `Ensemble` from
    what the generating activation consumed, so a participant never has to thread
    ids through itself.
    """
    recipients: tuple[str, ...] = ()
    """Whom the sender addressed this to — *selection*, in its own words.

    Empty means the sender named nobody and reachability decides, which is what
    a matcher-routed run looks like. Naming recipients is what a method whose
    agents choose their own correspondents needs, and the two compose: a
    declared recipient still has to be reachable for the message to arrive, and
    one that is not produces an event nothing was routed to — the thing
    `OrphanedEvent` is a query for.
    """

    terminal: bool = False
    """This message claims the whole task is done.

    A flag rather than a node type, so a terminal message is still an ordinary
    message that can be inspected, rerouted or un-terminated by a stage.
    """

    def with_lineage(self, parents: tuple[str, ...]) -> Envelope:
        """Copy carrying *parents*, keeping the same id."""
        return self.model_copy(update={"parents": parents})


class Brief(BaseModel):
    """What a participant is asked to do this round."""

    round: int = 0
    task: str = ""
    inbox: tuple[Envelope, ...] = ()
    """Routed messages. Populated in delivery mode only; empty in visibility
    mode, where peers arrive as tools instead."""

    @property
    def tags(self) -> dict[str, str]:
        """Short labels for this brief's inbox: `e1`, `e2`, ...

        An envelope id is a uuid, and a participant asked to say what it did
        with each incoming message needs something it can quote back without
        transcribing thirty-two hex characters. Per-brief rather than global:
        the tag is a handle for one turn, and the id remains what the record
        keeps.
        """
        return {e.id: f"e{i + 1}" for i, e in enumerate(self.inbox)}

    def resolve(self, tag: str) -> str | None:
        """The envelope id a tag refers to, accepting an id itself."""
        for message_id, label in self.tags.items():
            if tag in (label, message_id):
                return message_id
        return None

    def as_prompt(self) -> str:
        parts: list[str] = [self.task]
        if self.inbox:
            tags = self.tags
            parts.append("\nMessages from other agents:")
            parts.extend(
                f"- [{tags[e.id]}] {e.sender}: {e.content}" for e in self.inbox
            )
        return "\n".join(parts)


class Addressed(BaseModel):
    """One message a turn sends, and whom it is for."""

    to: tuple[str, ...] = Field(
        default=(),
        description="Names of the agents this message is for. Leave empty to let "
        "the topology decide who needs it.",
    )
    content: str = Field(default="", description="The message itself.")


class TurnPayload(BaseModel):
    """Structured output requested from a participant in a single pass.

    Message, addressing, reactions, query and key come back in one forward
    pass; asking for any of it in a second call would double the cost of every
    round for nothing.
    """

    message: str = Field(
        default="", description="Your answer or contribution this round."
    )
    private: str | None = Field(
        default=None,
        description="Optional message intended only for the agents that need it, "
        "with no particular addressee.",
    )
    messages: list[Addressed] = Field(
        default_factory=list,
        description="Messages for specific agents. Use this when different agents "
        "need different things — one entry per recipient group.",
    )
    query: str = Field(
        default="", description="What you need from other agents right now."
    )
    key: str = Field(
        default="", description="What you can offer other agents right now."
    )
    reactions: dict[str, str] = Field(
        default_factory=dict,
        description="What you did with each message you received, keyed by its "
        "[eN] tag: 'consume' if you acted on it, 'wait' to keep it for a later "
        "turn, 'discard' to drop it. Anything you do not mention counts as "
        "consumed.",
    )
    reroute: dict[str, list[str]] = Field(
        default_factory=dict,
        description="Messages you are handing to someone better placed to act on "
        "them, keyed by [eN] tag, valued by the agents to hand them to.",
    )
    submitted: bool = Field(
        default=False, description="True only when the overall task is complete."
    )


class Turn(BaseModel):
    """What a participant produced in one round.

    `outputs` is a list rather than a public/private pair because one
    activation can legitimately send a different thing to each of several
    agents — a coordinator splitting work five ways produces five messages, not
    one broadcast that five agents happen to read. `public` and `private`
    remain as accessors for the common case of one of each.
    """

    participant: str
    outputs: tuple[Envelope, ...] = ()
    """Every message this turn generated, in the order it declared them."""
    reactions: dict[str, Reaction] = Field(
        default_factory=dict,
        description="What this turn did with each delivered message, by envelope "
        "id. Absent means consumed — the same default the record has always had, "
        "now stated in one place.",
    )
    rerouted: dict[str, tuple[str, ...]] = Field(
        default_factory=dict,
        description="Delivered messages this turn handed on, by envelope id, and "
        "to whom. Selection again, one level down: not what to say, but who "
        "should have heard what was already said.",
    )
    query: str = ""
    """What this participant needs, in its own words. Used by a matching stage."""
    key: str = ""
    """What it can offer. The dynamic half of an advertisement — the AgentCard is
    the static half — and, like the card, written by the participant about itself."""
    invoked: tuple[str, ...] = ()
    """Peers this participant actually called — selection, as opposed to the
    reachability the topology granted."""
    submitted: bool = False
    error: str | None = None

    @property
    def public(self) -> Envelope | None:
        """This turn's contribution to the record, if it made one."""
        return next((e for e in self.outputs if e.visibility == "public"), None)

    @property
    def private(self) -> Envelope | None:
        """The first message meant for other agents rather than the record."""
        return next((e for e in self.outputs if e.visibility == "private"), None)

    @property
    def envelopes(self) -> tuple[Envelope, ...]:
        """Every message this turn produced. Alias for `outputs`."""
        return self.outputs

    def reaction_for(self, message_id: str) -> Reaction:
        """What this turn did with one delivered message."""
        return self.reactions.get(message_id, "consume")

    def consumed(self) -> tuple[str, ...]:
        """Ids of the delivered messages this turn actually took in."""
        return tuple(mid for mid, label in self.reactions.items() if label == "consume")

    def recorded(self, parents: tuple[str, ...]) -> Turn:
        """Normalised for the graph: lineage attributed, submission marked.

        Both facts are derived here rather than asked of the participant.
        Lineage is what the turn consumed, which the coordinator already knows
        — a message left waiting is not an ancestor of anything yet. And
        `submitted` is the single source of truth for "the task is done", so
        deriving `Envelope.terminal` from it means a `Participant` written by
        hand cannot set one and forget the other, which would silently disable
        every detector that looks for `e_inf`.
        """
        return self.model_copy(
            update={
                "outputs": tuple(
                    envelope.model_copy(
                        update={
                            "parents": parents,
                            "terminal": self.submitted
                            and envelope.visibility == "public",
                        }
                    )
                    for envelope in self.outputs
                )
            }
        )


@runtime_checkable
class Participant(Protocol):
    """An addressable actor that can be wired into a topology.

    Deliberately not a `BaseAgent`: local in-process agents and remote A2A
    peers must be interchangeable.
    """

    @property
    def name(self) -> str: ...

    @property
    def profile(self) -> ParticipantProfile: ...

    def act(
        self, brief: Brief, *, ctx: InvocationContext | None = None
    ) -> AsyncIterator[Event | Turn]:
        """Take one turn, yielding events and finally exactly one `Turn`."""
        ...

    def as_tool(self) -> Tool:
        """A tool that calls this participant, for peers that can reach it."""
        ...

    async def bind_peers(self, peers: Mapping[str, Participant]) -> bool:
        """Make exactly *peers* reachable, detaching any others.

        Returns:
            True if reachability was actually changed. False means this
            participant cannot be rebound — a remote A2A peer, for instance,
            since there is no operation for attaching a tool to an agent in
            another process.
        """
        ...


class PeerTool(Tool):
    """Calls another local participant, as `A2AAgentTool` does for a remote one.

    Bounded by *max_depth* so a chain of peers calling peers cannot recurse
    without limit inside a single round.
    """

    model_config = ConfigDict(arbitrary_types_allowed=True)

    max_depth: int = 3

    _target: Any = PrivateAttr(default=None)

    @classmethod
    def for_participant(cls, target: Participant, *, max_depth: int = 3) -> PeerTool:
        profile = target.profile
        tool = cls(
            name=f"call_{profile.name}",
            description=(
                f"Send a message to the '{profile.name}' agent and get its reply.\n\n"
                f"{profile.description}"
            ),
            parameters={
                "type": "object",
                "properties": {
                    "message": {
                        "type": "string",
                        "description": "The message to send. Include everything the agent needs.",
                    }
                },
                "required": ["message"],
            },
            max_depth=max_depth,
        )
        tool._target = target
        tool._attach_func()
        return tool

    def _attach_func(self) -> None:
        async def _call_peer(message: str) -> str:
            depth = _peer_depth.get()
            if depth >= self.max_depth:
                return (
                    f"Peer call rejected: maximum call depth {self.max_depth} reached. "
                    "Answer with what you already have."
                )
            token = _peer_depth.set(depth + 1)
            try:
                brief = Brief(task=message)
                last = ""
                async for item in self._target.act(brief):
                    if isinstance(item, Turn):
                        last = item.public.content if item.public else last
                    elif isinstance(item, FinalAnswerEvent):
                        last = item.content
                return last
            finally:
                _peer_depth.reset(token)

        self._func = _call_peer

    @property
    def is_namespace(self) -> Literal[False]:
        return False


class _BaseParticipant:
    """Shared peer-binding bookkeeping for the concrete adapters."""

    max_depth: int = 3

    def __init__(self) -> None:
        self._peer_tools: dict[str, Tool] = {}
        self._peer_tool_names: dict[str, str] = {}

    @property
    def bound_peers(self) -> frozenset[str]:
        return frozenset(self._peer_tools)

    def _resolve_invoked(self, tool_names: list[str]) -> tuple[str, ...]:
        seen: list[str] = []
        for tool_name in tool_names:
            peer = self._peer_tool_names.get(tool_name)
            if peer is not None and peer not in seen:
                seen.append(peer)
        return tuple(seen)


class LocalParticipant(_BaseParticipant):
    """A `BaseAgent` (optionally driven by a `Workflow`) as a participant.

    `Colony.agent()` already pairs an agent with a workflow, so a colony can
    build these directly from its specs.

    Query/key descriptors are elicited in the same pass as the turn via
    `response_schema`. That path is unavailable when a `Workflow` drives the
    run — `Workflow.stream` takes no schema — so workflow-backed participants
    fall back to their profile text for matching.
    """

    def __init__(
        self,
        agent: BaseAgent,
        *,
        workflow: Workflow[Any] | None = None,
        name: str | None = None,
        max_depth: int = 3,
    ) -> None:
        super().__init__()
        self.agent = agent
        self.workflow = workflow
        self._name = name or agent.name
        self.max_depth = max_depth

    @property
    def name(self) -> str:
        return self._name

    @property
    def profile(self) -> ParticipantProfile:
        return ParticipantProfile(
            name=self._name,
            description=self.agent.description or "",
        )

    def as_tool(self) -> Tool:
        return PeerTool.for_participant(self, max_depth=self.max_depth)

    async def bind_peers(self, peers: Mapping[str, Participant]) -> bool:
        desired = {n for n in peers if n != self._name}
        current = set(self._peer_tools)

        for gone in current - desired:
            tool = self._peer_tools.pop(gone)
            if tool.name:
                self._peer_tool_names.pop(tool.name, None)
                self.agent.remove_tool(tool.name)

        for added in desired - current:
            tool = peers[added].as_tool()
            self.agent.add_tool(tool)
            self._peer_tools[added] = tool
            if tool.name:
                self._peer_tool_names[tool.name] = added

        return True

    async def act(
        self, brief: Brief, *, ctx: InvocationContext | None = None
    ) -> AsyncIterator[Event | Turn]:
        state = State(messages=[Message(role="user", content=brief.as_prompt())])
        structured = self.workflow is None
        final = ""
        tool_names: list[str] = []

        if self.workflow is not None:
            stream = self.workflow.stream(self.agent, ctx=ctx, state=state)
        else:
            stream = self.agent.stream(state, ctx=ctx, response_schema=TurnPayload)

        async for event in stream:
            if isinstance(event, ToolCallingEvent):
                tool_names.extend(tc.function.name for tc in event.tool_calls)
            if (
                isinstance(event, FinalAnswerEvent)
                and event.content
                or event.kind == "completed"
                and event.content
            ):
                final = event.content
            yield event

        yield _build_turn(
            participant=self._name,
            raw=final,
            structured=structured,
            round=brief.round,
            invoked=self._resolve_invoked(tool_names),
            brief=brief,
        )


class A2AParticipant(_BaseParticipant):
    """A remote agent reachable over A2A, as a participant.

    Reuses `A2AAgentTool` for the call and its AgentCard rendering for the
    profile, so a remote peer advertises itself exactly as it does today.

    Peer *binding* is a no-op: A2A has no operation for attaching a tool to an
    agent in another process. Remote participants therefore adapt under
    `DeliveryMaterialiser`, where the coordinator routes their messages; under
    `VisibilityMaterialiser` their reachability stays as the colony wired it,
    and the materialiser reports them as unbindable rather than pretending.
    """

    def __init__(
        self,
        config: A2AConfig,
        card: AgentCard,
        *,
        name: str | None = None,
        max_depth: int = 3,
    ) -> None:
        super().__init__()
        self.config = config
        self.card = card
        self._name = name or card.name
        self.max_depth = max_depth

    @property
    def name(self) -> str:
        return self._name

    @property
    def profile(self) -> ParticipantProfile:
        tool = self.as_tool()
        tags: list[str] = []
        for skill in self.card.skills or []:
            tags.extend(skill.tags or [])
        return ParticipantProfile(
            name=self._name,
            description=tool.description or self.card.description or "",
            tags=tuple(dict.fromkeys(tags)),
        )

    def as_tool(self) -> Tool:
        from ant_ai.a2a.agent import A2AAgentTool

        tool = A2AAgentTool.from_config(config=self.config, agent_card=self.card)
        if not isinstance(tool, Tool):  # pragma: no cover - card is always supplied
            raise TypeError(
                "A2AAgentTool.from_config must return a Tool when a card is given."
            )
        return tool

    async def bind_peers(self, peers: Mapping[str, Participant]) -> bool:
        return False

    async def act(
        self, brief: Brief, *, ctx: InvocationContext | None = None
    ) -> AsyncIterator[Event | Turn]:
        tool = self.as_tool()
        raw = await tool.ainvoke(message=brief.as_prompt())
        yield _build_turn(
            participant=self._name,
            raw=str(raw),
            structured=False,
            round=brief.round,
            invoked=(),
            brief=brief,
        )


def _build_turn(
    *,
    participant: str,
    raw: str,
    structured: bool,
    round: int,
    invoked: tuple[str, ...],
    brief: Brief | None = None,
) -> Turn:
    """Parse a participant's raw output into a `Turn`.

    A malformed structured payload degrades to a plain public message rather
    than failing the round: a participant that ignores the schema should cost
    the matcher its descriptors, not abort the run.
    """
    payload: TurnPayload | None = None
    if structured and raw:
        try:
            payload = TurnPayload.model_validate_json(raw)
        except Exception:
            payload = None

    if payload is None:
        return Turn(
            participant=participant,
            outputs=(
                Envelope(
                    sender=participant, content=raw, visibility="public", round=round
                ),
            ),
            invoked=invoked,
        )

    outputs = [
        Envelope(
            sender=participant,
            content=payload.message,
            visibility="public",
            round=round,
        )
    ]
    if payload.private:
        outputs.append(
            Envelope(
                sender=participant,
                content=payload.private,
                visibility="private",
                round=round,
            )
        )
    outputs += [
        Envelope(
            sender=participant,
            content=addressed.content,
            visibility="private",
            round=round,
            recipients=tuple(addressed.to),
        )
        for addressed in payload.messages
        if addressed.content
    ]

    # Tags are per-brief handles, so they are resolved back to ids here — the
    # record keeps ids, and a participant that answered with an id rather than
    # a tag is understood either way.
    reactions: dict[str, Reaction] = {}
    rerouted: dict[str, tuple[str, ...]] = {}
    if brief is not None:
        for tag, label in payload.reactions.items():
            message_id = brief.resolve(tag)
            reaction = REACTIONS.get(label)
            if message_id is not None and reaction is not None:
                reactions[message_id] = reaction
        for tag, targets in payload.reroute.items():
            message_id = brief.resolve(tag)
            if message_id is None or not targets:
                continue
            rerouted[message_id] = tuple(targets)
            reactions[message_id] = "reroute"

    return Turn(
        participant=participant,
        outputs=tuple(outputs),
        reactions=reactions,
        rerouted=rerouted,
        query=payload.query,
        key=payload.key,
        invoked=invoked,
        submitted=payload.submitted,
    )
