from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, Field


class Message(BaseModel):
    """Generic message used in a conversation"""

    kind: Literal["message"] = Field(default="message")
    """Type of the message. Used to reconstruct, not passed to the LLM"""
    role: str
    """Role of the message sender (e.g. "user", "assistant")"""
    content: str | None = Field(default=None)
    """Text content of the message"""
    metadata: dict[str, Any] = Field(default_factory=dict)
    """Additional metadata associated with the message"""


class MessageChunk(BaseModel):
    """
    Represents *partial output* from an LLM during streaming.
    `delta` is the content's only the newly streamed text fragment,
    not the whole message so far.
    """

    role: str
    delta: str
    metadata: dict = Field(default_factory=dict)

    def merge(self, other: MessageChunk) -> MessageChunk:
        """Combines two MessageChunk into one

        Args:
            other (MessageChunk): The other message chunk to combine with

        Returns:
            MessageChunk: A combined chunk where this is before the other chunk
        """
        if self.role != other.role:
            raise ValueError("roles must match to merge")
        return MessageChunk(
            role=self.role,
            delta=self.delta + other.delta,
            metadata={**self.metadata, **other.metadata},
        )

    def to_message(self) -> Message:
        """Convert final chunk to a full message once streaming ends."""
        return Message(role=self.role, content=self.delta, metadata=self.metadata)


class ToolCallMessage(Message):
    """Message representing a tool call in a conversation"""

    kind: Literal["tool_call"] = Field(default="tool_call")
    role: str = "assistant"
    tool_calls: list[ToolCall]


class ToolCallResultMessage(Message):
    """Message representing the result of a tool call in a conversation"""

    kind: Literal["tool_call_result"] = Field(default="tool_call_result")
    role: str = "tool"
    tool_call_id: str
    name: str


class ToolFunction(BaseModel):
    """Inner function payload for a tool call (OpenAI schema)."""

    name: str
    """Name of the tool called"""
    # OpenAI expects a JSON string, not a dict.
    arguments: str
    """Arguments for the tool"""


class ToolCall(BaseModel):
    """Single tool call object inside assistant.tool_calls (OpenAI schema)."""

    id: str
    """Unique ID for the tool call, is generated by the OpenAI compatible endpoint"""
    type: str = "function"
    """Type of the tool call"""
    function: ToolFunction
    """Tool called"""


type AnyMessage = Annotated[
    Message | ToolCallMessage | ToolCallResultMessage,
    Field(discriminator="kind"),
]
"""Type alias for any message type in the system, discriminated by the `_kind` field."""
